name: gotest
description: "execute go tests based upon parameters"

runs:
  using: "composite"
  steps:
    - run: echo "PREFIX=gotests" >> $GITHUB_ENV
      shell: bash
      name: Set Unique Test prefix
    - uses: actions/setup-python@v2
      with:
        python-version: '~3.9.5'
      name: "Install Python (~3.9.5)"
    - run: python --version
      shell: bash
      name: "Check python installed"
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          awscli
          packaging
      name: "Install Python requirements with pip"
    - name: Install Go
      uses: ./.github/actions/setup-go
    - run: |
        go install gotest.tools/gotestsum@latest
      shell: bash
      name: "Install gotestsum (latest)"
    - name: make gotest
      shell: bash
      run: |
        export DEV_KUBE_NO_PVC=yes
        export KAT_REQ_LIMIT=900
        export TEST_XML_DIR=/tmp/test-logs/xml/
        export GOTEST_ARGS='-timeout 30m'
        mkdir -p ${TEST_XML_DIR}
        make gotest
    - uses: ./.github/actions/git-dirty-check
      name: "Check git not dirty from testing"
