apiVersion: v1
appVersion: 2.12.0-wip
ossVersion: 1.13.4
description: A Helm chart for Datawire Ambassador
name: ambassador
version: 6.9.6
icon: https://www.getambassador.io/images/logo.png
home: https://www.getambassador.io/
sources:
- https://github.com/datawire/ambassador
- https://github.com/prometheus/statsd_exporter
keywords:
- api gateway
- ambassador
- datawire
- envoy
maintainers:
- name: flydiverny
  email: markus@maga.se
- name: kflynn
  email: flynn@datawire.io
- name: nbkrause
  email: nkrause@datawire.io
- name: lukeshu
  email: lukeshu@datawire.io
engine: gotpl
