name: generate
description: "execute make generate twice, ensure git not dirty"

runs:
  using: "composite"
  steps:
    - name: "install bsdtar (libarchive-tools)"
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libarchive-tools
    - name: Install Go
      uses: ./.github/actions/setup-go
    - uses: actions/setup-python@v2
      with:
        python-version: '~3.9.5'
      name: "Install Python (~3.9.5)"
    - run: python --version
      shell: bash
      name: "Check python installed"
    - name: "'make generate'"
      shell: bash
      run: |
        make generate
    - uses: ./.github/actions/git-dirty-check
      name: "Check git not dirty from 'make generate'"
    - name: "'make generate' (again!)"
      shell: bash
      run: |
        make generate
    - uses: ./.github/actions/git-dirty-check
      name: "Check git not dirty from 'make generate' (again!)"
