{{- if and .Values.crds.enabled (not .Values.crds.keep)}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ambassador.serviceAccountName" . }}-crd-delete
  namespace: {{ include "ambassador.namespace" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    {{- include "ambassador.labels" . | nindent 4 }}
    product: aes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador.rbacName" . }}-crd-delete
  namespace: {{ include "ambassador.namespace" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    {{- include "ambassador.labels" . | nindent 4 }}
    product: aes
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ambassador.rbacName" . }}-crd-delete
  namespace: {{ include "ambassador.namespace" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    {{- include "ambassador.labels" . | nindent 4 }}
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ambassador.rbacName" . }}-crd-delete
subjects:
  - name: {{ include "ambassador.serviceAccountName" . }}-crd-delete
    namespace: {{ include "ambassador.namespace" . }}
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ambassador.fullname" . }}-crd-cleanup
  namespace: {{ include "ambassador.namespace" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "3"
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    {{- include "ambassador.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "ambassador.fullname" . }}-crd-cleanup
      labels:
        app.kubernetes.io/name: {{ include "ambassador.name" . }}
        {{- include "ambassador.labels" . | nindent 8 }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ include "ambassador.serviceAccountName" . }}-crd-delete
      {{- end }}
      containers:
        - name: kubectl
          image: "buoyantio/kubectl"
          args:
          - delete
          - crds
          - -l app.kubernetes.io/name=ambassador
      restartPolicy: OnFailure
{{- end }}
