{{- if .Values.createDefaultListeners }}
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorListener
metadata:
  name: {{ include "ambassador.fullname" . }}-https-listener
  namespace: {{ include "ambassador.namespace" . }}
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorListener
metadata:
  name: {{ include "ambassador.fullname" . }}-http-listener
  namespace: {{ include "ambassador.namespace" . }}
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
{{ end }}