{{- if .Values.rbac.create -}}

---
######################################################################
# No namespace                                                       #
######################################################################
# This ClusterRole should be limited to resource types that are
# non-namespaced, and therefore cannot be put in a Role, even if
# Emissary is in single-namespace mode.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador.rbacName" . }}-nonamespace
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    {{- end }}
    product: aes
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ambassador.rbacName" . }}-nonamespace
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    {{- end }}
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ambassador.rbacName" . }}-nonamespace
subjects:
  - name: {{ include "ambassador.serviceAccountName" . }}
    namespace: {{ include "ambassador.namespace" . }}
    kind: ServiceAccount

---
######################################################################
# All namespaces                                                     #
######################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.scope.singleNamespace }}Cluster{{ end }}Role
metadata:
  name: {{ include "ambassador.rbacName" . }}-allnamespaces
{{- if .Values.scope.singleNamespace }}
  namespace: {{ include "ambassador.namespace" . }}
{{- end }}
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    {{- end }}
    product: aes
rules:
  - apiGroups: [""]
    resources:
    - namespaces
    - services
    - secrets
    - endpoints
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "getambassador.io" ]
    resources: [ "*" ]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete" ]

  - apiGroups: [ "getambassador.io" ]
    resources: [ "mappings/status" ]
    verbs: ["update"]

  - apiGroups: [ "networking.internal.knative.dev" ]
    resources: [ "clusteringresses", "ingresses" ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "networking.x-k8s.io" ]
    resources: [ "*" ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "networking.internal.knative.dev" ]
    resources: [ "ingresses/status", "clusteringresses/status" ]
    verbs: ["update"]

  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources: [ "ingresses", "ingressclasses" ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources: [ "ingresses/status" ]
    verbs: ["update"]

  {{- if or .Values.rbac.podSecurityPolicies .Values.security.podSecurityPolicy }}

  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
    {{- if .Values.rbac.podSecurityPolicies }}
      {{- toYaml .Values.rbac.podSecurityPolicies | nindent 6 }}
    {{- end }}
    {{- if .Values.security.podSecurityPolicy }}
    - {{ include "ambassador.fullname" . }}
    {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.scope.singleNamespace }}Cluster{{ end }}RoleBinding
metadata:
  name: {{ include "ambassador.rbacName" . }}-allnamespaces
{{- if .Values.scope.singleNamespace }}
  namespace: {{ include "ambassador.namespace" . }}
{{- end }}
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    {{- end }}
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.scope.singleNamespace }}Cluster{{ end }}Role
  name: {{ include "ambassador.rbacName" . }}-allnamespaces
subjects:
  - name: {{ include "ambassador.serviceAccountName" . }}
    namespace: {{ include "ambassador.namespace" . }}
    kind: ServiceAccount

---
######################################################################
# One namespace                                                      #
######################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador.rbacName" . }}-onenamespace
  namespace: {{ include "ambassador.namespace" . }}
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    {{- end }}
    product: aes
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ambassador.rbacName" . }}-onenamespace
  namespace: {{ include "ambassador.namespace" . }}
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    {{- end }}
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador.rbacName" . }}-onenamespace
subjects:
  - name: {{ include "ambassador.serviceAccountName" . }}
    namespace: {{ include "ambassador.namespace" . }}
    kind: ServiceAccount

{{- end -}}
