name: pytest
on:
  push:

jobs:
  execute-go-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # NOTES:
        # legacy mode does not do fast reconfigure - never test state true, true
        # on master/release branch (legacy + reconfigure testing)
        #   - legacy + no reconfigure (true, false)
        #   -  no legacy + reconfigure (false, true)
        #   - no legacy + no reconfigure (false, false)
        # other branches (no legacy testing)
        #   - no legacy + no reconfigure (false, true)
        #   - no legacy + reconfigure (false, false)
        pytest-settings:
          - {legacy-mode: true, fast-reconfigure: false}
        isMasterOrRelease:
          # is this close enough to release branch being /^rel\/v[0-9]+\.[0-9]+\.[0-9]+(-ea)?$/ ?
          - ${{ contains(github.ref, 'master') || startsWith(github.ref, 'refs/heads/rel/v') }}
        exclude:
          - isMasterOrRelease: false # if we are not master/release then we exclude legacy mode
            pytest-settings: {legacy-mode: true, fast-reconfigure: false}
    name: (legacy-mode:${{ matrix.pytest-settings.legacy-mode }}, fast-reconfigure:${{ matrix.pytest-settings.fast-reconfigure }} )
    steps:
      - run: echo "PREFIX=legacy-mode.${{ matrix.pytest-settings.legacy-mode }}-fast-reconfigure.${{ matrix.pytest-settings.fast-reconfigure }}" >> $GITHUB_ENV
        name: Set Unique Test prefix (legacy-mode.${{ matrix.pytest-settings.legacy-mode }}-fast-reconfigure.${{ matrix.pytest-settings.fast-reconfigure }})
      - run: echo "USE_LOCAL_K3S_CLUSTER=1" >> $GITHUB_ENV
        name: "Set USE_LOCAL_K3S_CLUSTER=1"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Docker Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_BUILD_USERNAME }}
          password: ${{ secrets.DOCKER_BUILD_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_BUILD_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_BUILD_PASSWORD }}
      - name: "Configure Kubernetes cluster and Docker registry"
        env:
          DOCKER_BUILD_USERNAME: ${{ secrets.DOCKER_BUILD_USERNAME }}
          DOCKER_BUILD_PASSWORD: ${{ secrets.DOCKER_BUILD_PASSWORD }}
          DEV_REGISTRY: docker.io/datawiredev
        run: |
          make push
