name: job-promote-to-passed
on:
  workflow_run:
    workflows:
      #- chart-test # only executed on chart changes, can't depend on it
      - gotest
      - generate
      - lint-test
      - pytest
      - job-image
    types:
      - completed

jobs:
  promote-to-passed:
    runs-on: ubuntu-latest
    name: job-promote-to-passed
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.GH_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Workflow Run Wait (Execute if all dependent workflows complete successfully)
        uses: ahmadnassri/action-workflow-run-wait@v1.4.2
        with:
          timeout: 2700000 #45 min in ms
      - name: "promote build to passed"
        run: |
          make release/promote-oss/dev-to-passed-ci
